### ISSUE TITLE
Button Click is not working in IPAD in the File Mode

### ISSUE THREAD

**Issue by Parthasarathi-eng** [ptc-iot-sharing/ThingworxBarcodeScannerWidget#20]
File Explorer window is not opening whenever User clicks Barcode Button  in the IPAD Chrome. Some Times It requires multiple click to open the File Explorer window

**Comment by stefan-lacatus** [comment]
Can you share the specific configuration of the widget?
The easiest way to do it is to just export the mashup with the widget and attach it here.

Based on this I can try to reproduce your issue.

**Comment by Parthasarathi-eng** [comment]
[Mashups_DVC_Prod_PrimaryPackage_Barcode_MU.zip](https://github.com/ptc-iot-sharing/ThingworxBarcodeScannerWidget/files/6968545/Mashups_DVC_Prod_PrimaryPackage_Barcode_MU.zip)

here mashup attached
